# Generated by Django 5.2.15 on 2026-07-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('channel', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Card')], default='mobile_money', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('clickpesa_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('order_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.order')),
            ],
        ),
    ]
