# Generated by Django 5.2.15 on 2026-06-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('delivery', 'Delivery Personnel')], default='customer', max_length=20),
        ),
    ]
